sudo: false
language: python
matrix:
  include:
  - os: linux
    python: "2.7"
  - os: linux
    python: "3.5"
  - os: linux
    python: "3.6"
  - os: linux
    python: "3.7"
  - os: linux
    python: "3.8"
  - os: osx
    osx_image: xcode9.3
    language: shell
    python: "2.7"
    before_install:
        - python --version
        - pip install pytest --user
        - pip install codecov --user
    install: pip install ".[test]" --user
    script: python -m pytest  # pytest command won't be found
    after_success: python  -m codecov  # codecov command won't be found
  - os: osx
    osx_image: xcode9.4
    language: shell
    python: "3.6"
    before_install:
        - python --version
        - pip install pytest --user
        - pip install codecov --user
    install: pip install ".[test]" --user
    script: python -m pytest  # pytest command won't be found
    after_success: python  -m codecov  # codecov command won't be found
  - os: osx
    osx_image: xcode10.2
    language: shell
    python: "3.7"
    before_install:
        - python --version
        - pip install pytest --user
        - pip install codecov --user
    install: pip install ".[test]" --user
    script: python -m pytest  # pytest command won't be found
    after_success: python  -m codecov  # codecov command won't be found

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install openssl; fi

install:
#  - scripts/travis.sh pip install pip-accel
  - pip install -U setuptools
  - pip install coveralls
  - pip install --requirement=requirements-checks.txt
  - pip install --requirement=requirements-tests.txt
  - LC_ALL=C pip install .
script:
#  - scripts/travis.sh make check
  - make test
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
