language: python
matrix:
  include:
  - os: linux
    python: "3.5"
  - os: linux
    python: "3.6"
  - os: linux
    python: "3.7"
  - os: osx
    osx_image: xcode9.4
    language: shell
    python: "3.6"
    script: python -m pytest  # pytest command won't be found
  - os: osx
    osx_image: xcode10.2
    language: shell
    python: "3.7"
    script: python -m pytest  # pytest command won't be found
  - os: windows
    language: shell
    python: "3.5"
    before_install:
      - choco install python --version 3.5.9
      - python --version
      - python -m pip install --upgrade pip
      - pip3 install --upgrade pytest
      - pip3 install codecov
    env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    script: python -m pytest
  - os: windows
    language: shell
    python: "3.6"
    before_install:
      - choco install python --version 3.6.10
      - python --version
      - python -m pip install --upgrade pip
      - pip3 install --upgrade pytest
      - pip3 install codecov
    env: PATH=/c/Python36:/c/Python35/Scripts:$PATH
    script: python -m pytest
  - os: windows
    language: shell
    python: "3.7"
    before_install:
      - choco install python --version 3.7.6
      - python --version
      - python -m pip install --upgrade pip
      - pip3 install --upgrade pytest
      - pip3 install codecov
    env: PATH=/c/Python37:/c/Python35/Scripts:$PATH
    script: python -m pytest

before_install:
  - python --version
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install openssl; fi

install:
  - pip install pytest
  - pip install codecov
  - pip install -U setuptools
  - pip install coveralls
  - pip install --requirement=requirements-checks.txt
  - pip install --requirement=requirements-tests.txt
  - LC_ALL=C pip install .
script:
  - make test
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
