language: python
matrix:
  include:
  - os: linux
    python: 2.7
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
  - os: linux
    python: 3.7
  - os: osx
    osx_image: xcode9.3
    language: shell
    python: 2.7
    before_install:
        - python --version
        - pip install --user --upgrade pip
        - pip install --user --upgrade pytest
    install:
        - pip install --user --requirement=requirements-checks.txt
        - pip install --user --requirement=requirements-tests.txt
    script: python -m pytest
    after_success: python -m codecov
  - os: osx
    osx_image: xcode9.4
    language: shell
    python: 3.6
    before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install --requirement=requirements-checks.txt
        - pip3 install --requirement=requirements-tests.txt
    script: python3 -m pytest
    after_success: python3 -m codecov
  - os: osx
    osx_image: xcode10.2
    language: shell
    python: 3.7
    before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install --requirement=requirements-checks.txt
        - pip3 install --requirement=requirements-tests.txt
    script: python3 -m pytest
    after_success: python3 -m codecov
  - os: windows
    language: shell
    python: 3.5
    before_install:
      - choco install python --version 3.5.4
      - python --version
      - python -m pip install --upgrade pip
      - python -m pip install pywin32
#      - pip install --upgrade pytest
#      - python -m pip install --upgrade pytest
#      - pip3 install codecov
    env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    script: python -m pytest
  - os: windows
    language: shell
    python: 3.6
    before_install:
      - choco install python --version 3.6.8
      - python --version
      - python -m pip install pywin32
      - python -m pip install --upgrade pip
#      - pip install --upgrade pytest
#      - python -m pip install --upgrade pytest
#      - pip3 install codecov
    env: PATH=/c/Python36:/c/Python35/Scripts:$PATH
    script: python -m pytest
  - os: windows
    language: shell
    python: 3.7
    before_install:
      - choco install python --version 3.7.3
      - python --version
      - python -m pip install pywin32
      - python -m pip install --upgrade pip
#      - python -m pip install --upgrade pytest
#      - pip install --upgrade pytest
#      - pip3 install codecov
    env: PATH=/c/Python37:/c/Python35/Scripts:$PATH
    script: python -m pytest

#before_install:
#  - python --version
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install openssl; fi

install:
  - python -m pip install pytest
#  - pip install codecov
  - python -m pip install -U setuptools
#  - pip install coveralls
  - python -m pip install --requirement=requirements-checks.txt
  - python -m pip install --requirement=requirements-tests.txt
#  - LC_ALL=C pip install .
script: 
  - python -m pytest
#script:
#  - make test
#after_success:
#  - coveralls
branches:
  except:
    - /^[0-9]/
